apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "observability_teste3"
  annotations:
    github.com/project-slug: sandrojrcorp/observability_teste3
    backstage.io/techdocs-ref: dir:.
    vault.io/secrets-path: devportal
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
